//Default booklist

module.exports = [
    //10 classics
    {
        title: "The Three Musketeers",
        author: "Alexandre Dumas",
        genre: "Adventure",
        tags: ["Classics", "Adventure", "Romance"],
        recommended: null,
        id: 0,
        favorites: false,
        original: true,
        read: false
    },
    {
        title: "Moby Dick",
        author: "Herman Melville",
        genre: "Fiction",
        tags: ["Classics", "Adventure"],
        recommended: null,
        id: 1,
        favorites: false,
        original: true,
        read: false
    },
    {
        title: "1984",
        author: "George Orwell",
        genre: "Fiction",
        tags: ["Fiction", "Politics", "Dystopia", "Classics"],
        recommended: null,
        id: 2,
        favorites: false,
        original: true,
        read: false
    },
    {
        title: "Crime and Punishment",
        author: "Fyodor Dostoyevsky",
        genre: "Fiction",
        tags: ["Fiction", "Philosophy", "Classics"],
        recommended: null,
        id: 3,
        favorites: false,
        original: true,
        read: false
    },
    {
        title: "Frankenstein",
        author: "Mary Shelley",
        genre: "Fiction",
        tags: ["Fiction", "Horror", "Classics"],
        recommended: null,
        id: 4,
        favorites: false,
        original: true,
        read: false
    },
    {
        title: "A Tale of Two Cities",
        author: "Charles Dickens",
        genre: "Fiction",
        tags: ["Historical Fiction", "Fiction", "Classics"],
        recommended: null,
        id: 5,
        favorites: false,
        original: true,
        read: false
    },
    {
        title: "The Adventures of Huckleberry Finn",
        author: "Mark Twain",
        genre: "Fiction",
        tags: ["Fiction", "Adventure", "Classics"],
        recommended: null,
        id: 6,
        favorites: false,
        original: true,
        read: false
    },
    {
        title: "Jane Eyre",
        author: "Charlotte Bronte",
        genre: "Romance",
        tags: ["Romance", "Fiction", "Classics"],
        recommended: null,
        id: 7,
        favorites: false,
        original: true,
        read: false
    },
    {
        title: "The Picture of Dorian Gray",
        author: "Oscar Wilde",
        genre: "Fiction",
        tags: ["Fiction", "Classics"],
        recommended: null,
        id: 8,
        favorites: false,
        original: true,
        read: false
    },
    {
        title: "The Great Gatsby",
        author: "F. Scott Fitzgerald",
        genre: "Fiction",
        tags: ["Fiction", "Classics"],
        recommended: null,
        id: 9,
        favorites: false,
        original: true,
        read: false
    },
    //10 science fiction
    {
        title: "Pandora's Star",
        author: "Peter F. Hamilton",
        genre: "Science Fiction",
        tags: ["Science Fiction"],
        recommended: null,
        id: 10,
        favorites: false,
        original: true,
        read: false
    },
    {
        title: "Dune",
        author: "Frank Herbert",
        genre: "Science Fiction",
        tags: ["Science Fiction"],
        recommended: null,
        id: 11,
        favorites: false ,
        original: true,
        read: false
    },
    {
        title: "Ready Player One",
        author: "Ernest Cline",
        genre: "Science Fiction",
        tags: ["Science Fiction"],
        recommended: null,
        id: 12,
        favorites: false,
        original: true,
        read: false
    },
    {
        title: "The Martian",
        author: "David Weis",
        genre: "Science Fiction",
        tags: ["Science Fiction"],
        recommended: null,
        id: 13,
        favorites: false,
        original: true,
        read: false
    },
    {
        title: "Ender's Game",
        author: "Orson Scott Card",
        genre: "Science Fiction",
        tags: ["Science Fiction"],
        recommended: null,
        id: 14,
        favorites: false,
        original: true,
        read: false
    },
    {
        title: "Leviathan Wakes",
        author: "James S.A. Corey",
        genre: "Science Fiction",
        tags: ["Science Fiction"],
        recommended: null,
        id: 15,
        favorites: false,
        original: true,
        read: false
    },
    {
        title: "Stranger in a Strange Land",
        author: "Robert A. Heinlein",
        genre: "Science Fiction",
        tags: ["Science Fiction"],
        recommended: null,
        id: 16,
        favorites: false,
        original: true,
        read: false
    },
    {
        title: "The Time Machine",
        author: "H.G. Wells",
        genre: "Science Fiction",
        tags: ["Science Fiction"],
        recommended: null,
        id: 17,
        favorites: false,
        original: true,
        read: false
    },
    {
        title: "Brave New World",
        author: "Aldous Huxley",
        genre: "Science Fiction",
        tags: ["Science Fiction"],
        recommended: null,
        id: 18,
        favorites: false,
        original: true,
        read: false
    },
    {
        title: "A Canticle for Leibowitz",
        author: "Walter M. Miller",
        genre: "Science Fiction",
        tags: ["Science Fiction"],
        recommended: null,
        id: 19,
        favorites: false,
        original: true,
        read: false
    },
    //10 fantasy
    {
        title: "Six of Crows",
        author: "Leigh Bardugo",
        genre: "Fantasy",
        tags: ["Fantasy"],
        recommended: null,
        id:  20,
        favorites: false  ,
        original: true,
        read: false
    },
    {
        title: "Daughter of the Forest",
        author: "Juliet Marillier",
        genre: "Fantasy",
        tags: ["Fantasy"],
        recommended: null,
        id: 21,
        favorites: false,
        original: true,
        read: false
    },
    {
        title: "Game of Thrones",
        author: "George R.R. Martin",
        genre: "Fantasy",
        tags: ["Fantasy"],
        recommended: null,
        id: 22,
        favorites: false,
        original: true,
        read: false
    },
    {
        title: "The Book of Flying",
        author: "Keith Miller",
        genre: "Fantasy",
        tags: ["Fantasy"],
        recommended: null,
        id: 23,
        favorites: false,
        original: true,
        read: false
    },
    {
        title: "The Name of the Wind",
        author: "Patrick Rothfuss",
        genre: "Fantasy",
        tags: ["Fantasy"],
        recommended: null,
        id: 24,
        favorites: false,
        original: true,
        read: false
    },
    {
        title: "The Way of Kings",
        author: "Brandon Sanderson",
        genre: "Fantasy",
        tags: ["Fantasy"],
        recommended: null,
        id: 25,
        favorites: false,
        original: true,
        read: false
    },
    {
        title: "The Fellowship of the Ring",
        author: "J.R.R. Tolkien",
        genre: "Fantasy",
        tags: ["Fantasy"],
        recommended: null,
        id: 26,
        favorites: false,
        original: true,
        read: false
    },
    {
        title: "Dealing with Dragons",
        author: "Patricia C. Wrede",
        genre: "Fantasy",
        tags: ["Fantasy"],
        recommended: null,
        id: 27,
        favorites: false,
        original: true,
        read: false
    },
    {
        title: "The Lion, the Witch and the Wardrobe",
        author: "C.S. Lewis",
        genre: "Fantasy",
        tags: ["Fantasy"],
        recommended: null,
        id: 28,
        favorites: false,
        original: true,
        read: false
    },
    {
        title: "The Blade Itself",
        author: "Joe Abercrombie",
        genre: "Fantasy",
        tags: ["Fantasy"],
        recommended: null,
        id: 29,
        favorites: false,
        original: true,
        read: false
    },
    //
    {
        title: "A Forest of Kings: The Untold Story of the Ancient Maya",
        author: "Linda Schele",
        genre: "History",
        tags: ["History"],
        recommended: null,
        id: 30,
        favorites: false,
        original: true,
        read: false
    },
    {
        title: "Guns, Germs, and Steel",
        author: "Jared Diamond",
        genre: "History",
        tags: ["History"],
        recommended: null,
        id: 31,
        favorites: false,
        original: true,
        read: false
    },
    {
        title: "History of the Peloponnesian War",
        author: "Thucydides",
        genre: "History",
        tags: ["History"],
        recommended: null,
        id: 32,
        favorites: false,
        original: true,
        read: false
    },
    {
        title: "The Art of War",
        author: "Sun Tzu",
        genre: "History",
        tags: ["History"],
        recommended: null,
        id: 33,
        favorites: false,
        original: true,
        read: false
    },
    {
        title: "A People's History of the United States",
        author: "Howard Zinn",
        genre: "History",
        tags: ["History"],
        recommended: null,
        id: 34,
        favorites: false,
        original: true,
        read: false
    },
    {
        title: "Cleopatra: A Life",
        author: "Stacy Schiff",
        genre: "History",
        tags: ["History"],
        recommended: null,
        id: 35,
        favorites: false,
        original: true,
        read: false
    },
    {
        title: "The Diary of a Young Girl",
        author: "Anne Frank",
        genre: "History",
        tags: ["History"],
        recommended: null,
        id: 36,
        favorites: false,
        original: true,
        read: false
    },
    {
        title: "The Success and Failure of Picasso",
        author: "John Berger",
        genre: "History",
        tags: ["History"],
        recommended: null,
        id: 37,
        favorites: false,
        original: true,
        read: false
    },
    {
        title: "Sapiens: A Brief History of Humankind",
        author: "Yuval Noah Harari",
        genre: "History",
        tags: ["History"],
        recommended: null,
        id: 38,
        favorites: false,
        original: true,
        read: false
    },
    {
        title: "Mummies, Disease and Ancient Cultures",
        author: "Aiden Cockburn",
        genre: "History",
        tags: ["History"],
        recommended: null,
        id: 39,
        favorites: false,
        original: true,
        read: false
    },
    //Biography
    {
        title: "The Glass Castle",
        author: "Jeannette Walls",
        genre: "Autobiography",
        tags: ["Autobiography"],
        recommended: null,
        id: 40,
        favorites: false,
        original: true,
        read: false
    },
    {
        title: "Yes Please",
        author: "Amy Poehler",
        genre: "Autobiography",
        tags: ["Autobiography"],
        recommended: null,
        id: 41,
        favorites: false,
        original: true,
        read: false
    },
    {
        title: "Judy Garland on Judy Garland: Interviews and Encounters",
        author: "Judy Garland",
        genre: "Autobiography",
        tags: ["Autobiography"],
        recommended: null,
        id: 42,
        favorites: false,
        original: true,
        read: false
    },
    {
        title: "My Life in Orange: Growing up with the Guru",
        author: "Tim Guest",
        genre: "Autobiography",
        tags: ["Autobiography"],
        recommended: null,
        id: 43,
        favorites: false,
        original: true,
        read: false
    },
    {
        title: "Orange is the New Black",
        author: "Piper Kerman",
        genre: "Autobiography",
        tags: ["Autobiography"],
        recommended: null,
        id: 44,
        favorites: false,
        original: true,
        read: false
    },
    {
        title: "Speak, Memory",
        author: "Vladimir Nabokov",
        genre: "Autobiography",
        tags: ["Autobiography"],
        recommended: null,
        id: 45,
        favorites: false,
        original: true,
        read: false
    },
    {
        title: "Insomniac Dreams: Experiments with Time",
        author: "Vladimir Nabokov",
        genre: "Autobiography",
        tags: ["Autobiography"],
        recommended: null,
        id: 46,
        favorites: false,
        original: true,
        read: false
    },
    {
        title: "The Hiding Place: The Triumphant True Story of Corrie Ten Boom",
        author: "Corrie ten Boom",
        genre: "Autobiography",
        tags: ["Autobiography"],
        recommended: null,
        id: 47,
        favorites: false,
        original: true,
        read: false
    },
    {
        title: "Confessions of an Actor",
        author: "Laurence Olivier",
        genre: "Autobiography",
        tags: ["Autobiography"],
        recommended: null,
        id: 48,
        favorites: false,
        original: true,
        read: false
    },
    {
        title: "Growing up Amish",
        author: "Ira Wagler",
        genre: "Autobiography",
        tags: ["Autobiography"],
        recommended: null,
        id: 49,
        favorites: false,
        original: true,
        read: false
    },
    //Fiction
    {
        title: "Do Androids Dream of Electric Sheep",
        author: "Phillip K. Dick",
        genre: "Fiction",
        tags: ["Fiction"],
        recommended: null,
        id: 50,
        favorites: false,
        original: true,
        read: false
    },
    {
        title: "David Copperfield",
        author: "Charles Dickens",
        genre: "Fiction",
        tags: ["Fiction"],
        recommended: null,
        id: 51,
        favorites: false ,
        original: true,
        read: false
    },
    {
        title: "American Psycho",
        author: "Bret Easton Ellis",
        genre: "Fiction",
        tags: ["Fiction"],
        recommended: null,
        id: 52,
        favorites: false,
        original: true,
        read: false
    },
    {
        title: "The Catcher in the Rye",
        author: "J.D. Salinger",
        genre: "Fiction",
        tags: ["Fiction"],
        recommended: null,
        id: 53,
        favorites: false,
        original: true,
        read: false
    },
    {
        title: "American Gods",
        author: "Neil Gaiman",
        genre: "Fiction",
        tags: ["Fiction"],
        recommended: null,
        id: 54,
        favorites: false,
        original: true,
        read: false
    },
    {
        title: "The Wind in the Willows",
        author: "Kenneth Grahame",
        genre: "Fiction",
        tags: ["Fiction"],
        recommended: null,
        id: 55,
        favorites: false,
        original: true,
        read: false
    },
    {
        title: "Red Harvest",
        author: "Dashiell Hammett",
        genre: "Fiction",
        tags: ["Fiction"],
        recommended: null,
        id: 56,
        favorites: false,
        original: true,
        read: false
    },
    {
        title: "The Kite Runner",
        author: "Khaled Hosseini",
        genre: "Fiction",
        tags: ["Fiction"],
        recommended: null,
        id: 57,
        favorites: false,
        original: true,
        read: false
    },
    {
        title: "Three Men in a Boat",
        author: "Jerome K. Jerome",
        genre: "Fiction",
        tags: ["Fiction"],
        recommended: null,
        id: 58,
        favorites: false,
        original: true,
        read: false
    },
    {
        title: "Gone with the Wind",
        author: "Margaret Mitchell",
        genre: "Fiction",
        tags: ["Fiction"],
        recommended: null,
        id: 59,
        favorites: false,
        original: true,
        read: false
    },
]

//format for books
// {
//     title: "",
//     author: "",
//     genre: "",
//     tags: [],
//     recommended: null,
//     id: 
// },